### ISSUE TITLE
Access the list of countries supported for IBAN

### ISSUE THREAD

**Issue by manosbatsis** [datafaker-net/datafaker#1001]
There is no easy way to control target country randomization when creating IBANs, because both `countryCodeToBasicBankAccountNumberPattern` and `createCountryCodeToBasicBankAccountNumberPatternMap()` are private in [Finance](https://github.com/datafaker-net/datafaker/blob/main/src/main/java/net/datafaker/providers/base/Finance.java).

If an unsupported country  (by `faker.country().countryCode2()`) is given as input to `iban(country)` it produces an NPE:

```
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.base/java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:105) ~[na:na]
        at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:131) ~[na:na]
        at net.datafaker.shaded.generex.Generex.requote(Generex.java:417) ~[datafaker-2.0.2.jar:2.0.2]
        at net.datafaker.shaded.generex.Generex.<init>(Generex.java:84) ~[datafaker-2.0.2.jar:2.0.2]
        at net.datafaker.shaded.generex.Generex.<init>(Generex.java:76) ~[datafaker-2.0.2.jar:2.0.2]
        at net.datafaker.service.FakeValuesService.regexify(FakeValuesService.java:338) ~[datafaker-2.0.2.jar:2.0.2]
        at net.datafaker.providers.base.BaseFaker.regexify(BaseFaker.java:174) ~[datafaker-2.0.2.jar:2.0.2]
        at net.datafaker.providers.base.Finance.iban(Finance.java:107) ~[datafaker-2.0.2.jar:2.0.2]
```

I'll add a PR with a Finance.ibanCountryCodes() to allow finer control of scope.

**Comment by bodiam** [comment]
Hi @manosbatsis , great to see you here. A PR would be very welcome to address this issue! Thanks!
