### ISSUE TITLE
java.lang.RuntimeException: Unable to resolve #{PhoneNumber.subscriber_number} directive for FakerContext when running continuously under very high load and limited heap space

### ISSUE THREAD

**Issue by sangeet-ushur** [datafaker-net/datafaker#1019]
**Description**
Faking phone number is throwing runtime error. I've seen this when running continuously under very high load and limited heap space(using Xmx).

**Stack trace**
```
 java.lang.RuntimeException: Unable to resolve #{PhoneNumber.subscriber_number} directive for FakerContext FakerContext{, locale=SingletonLocale{locale=en}, randomService=net.datafaker.service.RandomService@1d2939f5}.
        at net.datafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:585)
        at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:448)
        at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:424)
        at net.datafaker.providers.base.AbstractProvider.resolve(AbstractProvider.java:18)
        at net.datafaker.providers.base.PhoneNumber.cellPhone(PhoneNumber.java:13)
```

**To reproduce**
String valueMasked = (new Faker(new Random(valueToMask.hashCode()))).phoneNumber().cellPhone();
This is coming highly intermittently with some random valueToMask.

**Expected behavior**
Anonymised phone number should come.

**Versions:**
 - OS: CentOS Linux, Version 7
 - JDK 17
 - Faker Version 2.0.2

**Additional context**
None

**Comment by kingthorin** [comment]
How limited is your setting? Without specifics it'll be hard/impossible to recreate.

**Comment by sangeet-ushur** [comment]
Xms=400MB and Xmx=2GB

**Comment by kingthorin** [comment]
> Could you provide an example of valueToMask?

**Comment by sangeet-ushur** [comment]
I don't have the value with me as it was not logged.
The service had thrown `java.lang.OutOfMemoryError: Java heap space` and after that the following error was also thrown:
```
[1078.962s][warning][gc,alloc] anonymization-pool-17: Retried waiting for GCLocker too often allocating 256 words
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.HashMap.resize(HashMap.java:702)
        at java.base/java.util.HashMap.putVal(HashMap.java:627)
        at java.base/java.util.HashMap.putMapEntries(HashMap.java:514)
        at java.base/java.util.HashMap.putAll(HashMap.java:783)
[1078.970s][warning][gc,alloc] anonymization-pool-18: Retried waiting for GCLocker too often allocating 65538 words
        at net.datafaker.internal.helper.COWMap.put(COWMap.java:45)
        at net.datafaker.service.FakeValuesService.resExp(FakeValuesService.java:677)
        at net.datafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:582)
        at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:448)
        at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:424)
        at net.datafaker.providers.base.AbstractProvider.resolve(AbstractProvider.java:18)
        at net.datafaker.providers.base.PhoneNumber.cellPhone(PhoneNumber.java:13)
```
There were multiple logs of GC waiting: `Retried waiting for GCLocker too often allocating 256 words`. Eventually the logger also stops working hence I don't have the value with me. The error is occurring after the OOM issue.

Not sure if the above error is happening because of degraded performance after the OOM Exception.

**Comment by snuyanzin** [comment]
in case you have OOM i would expect you have heapdump and could provide some info about leak report or denominator report
could you please share this info?

**Comment by snuyanzin** [comment]
@sangeet-ushur can you perform your test agaisnst #1021 to see wether the issue is still present or not?
