### ISSUE TITLE
2.3.0 Release

### ISSUE THREAD

**Issue by bodiam** [datafaker-net/datafaker#1235]
# 2.3.0 Release

Anything specific we'd like to get in? I'm keen to get the image generation released.

**Comment by asolntsev** [comment]
Great, waiting for the release!

**Comment by bodiam** [comment]
Just wanted to make sure everyone got their stuff in, but I'll probably create a new release within the next week or so.

There's a lot of new stuff in it, mostly thanks to you @asolntsev . Absolutely appreciate your efforts here, amazing work!

**Comment by kingthorin** [comment]
Agreed. Thanks @asolntsev !!

To the original question I have nothing pressing outstanding for release.

**Comment by bodiam** [comment]
In that case I think I'll aim to release it tomorrow, let's see if the new github action works, otherwise I'll release it by hand.

**Comment by asolntsev** [comment]
@bodiam Hi. What about release 2.3.0?

**Comment by bodiam** [comment]
@asolntsev working on something to promote the release, took a bit longer than expected, but it's coming!

**Comment by asolntsev** [comment]
@bodiam Hi. How is release going?
P.S. I suggest we don't need to wait for https://github.com/datafaker-net/datafaker/pull/1271 and some other PRs - they can be released later as well.

**Comment by bodiam** [comment]
@asolntsev any objection to take #12 7 1 release? I'm happy to release it today.

**Comment by asolntsev** [comment]
@bodiam no objections. It would be great to release all these changes.

**Comment by bodiam** [comment]
I've been running 3 issues so far for creating the release. It's tricky.

This is the latest issue:

```
    [ERROR] net.datafaker.integration.FakerIntegrationTest.testAllFakerMethodsThatReturnStrings(Locale, Random)[55] -- Time elapsed: 0.662 s <<< ERROR!
    java.lang.RuntimeException: Test for method public java.lang.String net.datafaker.providers.base.IdNumber.valid() and object net.datafaker.providers.base.IdNumber@7c180af6 was failed for locale sv
        at net.datafaker.integration.FakerIntegrationTest.testAllMethodsThatReturnStringsActuallyReturnStrings(FakerIntegrationTest.java:115)
        at net.datafaker.integration.FakerIntegrationTest.testAllFakerMethodsThatReturnStrings(FakerIntegrationTest.java:94)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
    Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor446.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.datafaker.integration.FakerIntegrationTest.testAllMethodsThatReturnStringsActuallyReturnStrings(FakerIntegrationTest.java:113)
        ... 8 more
    Caused by: java.lang.RuntimeException: Unable to resolve #{IDNumber.ssn_valid} directive for FakerContext FakerContext{SingletonLocale{sv}, net.datafaker.service.RandomService@1}.
        at net.datafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:657)
        at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:522)
        at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:494)
        at net.datafaker.providers.base.BaseFaker.resolve(BaseFaker.java:366)
        at net.datafaker.providers.base.IdNumber.lambda$valid$1(IdNumber.java:42)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at net.datafaker.providers.base.IdNumber.valid(IdNumber.java:42)
        ... 12 more
```

**Comment by bodiam** [comment]
And for some reason I'm getting this error now:

```
    [INFO] Performing remote staging...
    [INFO] 
    [INFO]  * Remote staging into staging profile ID "639312c949acb3"
    [INFO]  * Created staging repository with ID "netdatafaker-1025".
    [INFO]  * Staging repository at https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/netdatafaker-1025
    [INFO]  * Uploading locally staged artifacts to profile net.datafaker
    Uploading to ossrh: https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/netdatafaker-1025/net/datafaker/datafaker/2.3.0/datafaker-2.3.0.jar.asc
    [ERROR] Remote staging finished with a failure: Failed to deploy artifacts: Could not transfer artifact net.datafaker:datafaker:jar.asc:2.3.0 from/to ossrh (https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/netdatafaker-1025): status code: 401, reason phrase: Content access is protected by token (401)
```

**Comment by bodiam** [comment]
Seems that Maven central changed a thing: 

https://central.sonatype.org/faq/401-error/#answer
https://central.sonatype.org/publish/generate-token/

**Comment by bodiam** [comment]
Okay, that only took a few too many attempts, but the release is done now.
