### ISSUE TITLE
2.4.0 regression: intermittent NPE in net.datafaker.service.FakeValuesService.retrieveMethodAccessor(FakeValuesService.java:966)

### ISSUE THREAD

**Issue by axelfontaine** [datafaker-net/datafaker#1403]
**Describe the bug**
After upgrading to 2.4.0, tests run by Gradle fail randomly with this NPE:

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "accessorMap" is null
      at net.datafaker.service.FakeValuesService.retrieveMethodAccessor(FakeValuesService.java:966)
      at net.datafaker.service.FakeValuesService.resolveFromMethodOn(FakeValuesService.java:920)
      at net.datafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:788)
      at net.datafaker.service.FakeValuesService.resExp(FakeValuesService.java:733)
      at net.datafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:648)
      at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:516)
      at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:492)
      at net.datafaker.providers.base.AbstractProvider.resolve(AbstractProvider.java:20)
      at net.datafaker.providers.base.Name.name(Name.java:27)
```

This is most likely due to a concurrency issue while initializing the providers when multiple tests access the library in parallel. If confirmed the initialization should be reworked to be thread-safe.

**To Reproduce**
```kotlin
Faker().name().name()
```

**Expected behavior**
A fake name, no NPE.

**Versions:**
 - OS: Win11 x64
 - JDK: 22
 - Faker Version: 2.4.0

**Additional context**
Reverting to 2.3.0 with no other changes fixes the issue.

**Comment by asolntsev** [comment]
@axelfontaine I think this problem is already fixed by PR https://github.com/datafaker-net/datafaker/pull/1381/files

@bodiam @kingthorin We need to release DataFaker 2.4.1

**Comment by bodiam** [comment]
@asolntsev @axelfontaine @kingthorin I'll release a new version this weekend.
